In [1]:
!pip install graphviz==0.10 --user

In [2]:
import pandas as pd
import graphviz
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split, cross_validate, KFold, StratifiedKFold, GroupKFold
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.pipeline import Pipeline

In [3]:
uri = "https://gist.githubusercontent.com/guilhermesilveira/e99a526b2e7ccc6c3b70f53db43a87d2/raw/1605fc74aa778066bf2e6695e24d53cf65f2f447/machine-learning-carros-simulacao.csv"

dados = pd.read_csv(uri).drop(columns=["Unnamed: 0"], axis=1)

dados.head()

preco  vendido  idade_do_modelo   km_por_ano
0   30941.02        1               18  35085.22134
1   40557.96        1               20  12622.05362
2   89627.50        0               12  11440.79806
3   95276.14        0                3  43167.32682
4  117384.68        1                4  12770.11290

In [4]:
renome = {
    'km_por_ano': 'km_ano',
    'idade_do_modelo': 'idade',
    'price': 'preco',
    'sold': 'vendido'
}
dados = dados.rename(columns=renome)
dados.head()

preco  vendido  idade       km_ano
0   30941.02        1     18  35085.22134
1   40557.96        1     20  12622.05362
2   89627.50        0     12  11440.79806
3   95276.14        0      3  43167.32682
4  117384.68        1      4  12770.11290

In [5]:

dados.head()

preco  vendido  idade       km_ano
0   30941.02        1     18  35085.22134
1   40557.96        1     20  12622.05362
2   89627.50        0     12  11440.79806
3   95276.14        0      3  43167.32682
4  117384.68        1      4  12770.11290

In [6]:
soma_modelo = np.random.randint(-2, 3, size=10000)
dados['modelo'] = dados.idade + soma_modelo


In [7]:
dados.head()
dados.modelo.unique()
dados['modelo'] = dados.modelo + abs(dados.modelo.min()) + 1
dados.modelo.unique()

array([21, 20, 15,  4,  8, 12, 17, 13, 22, 16,  6, 11, 19, 14,  3,  7,  9,
       18, 23, 10, 24,  5,  2,  1], dtype=int64)

In [8]:
x = dados[['preco', 'idade', 'km_ano']]
y = dados['vendido']

In [9]:
SEED = 158020
np.random.seed = 158020

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, random_state = SEED, test_size = 0.25, stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC(random_state = SEED)
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 7500 elementos e testaremos com 2500 elementos
A acurácia foi 60.12%


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [10]:
dummy = DummyClassifier()

dummy.fit(treino_x, treino_y)
previsoes = dummy.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 58.00%


In [11]:
dummy = DummyClassifier()

dummy.fit(treino_x, treino_y)

acuracia = dummy.score(teste_x, teste_y) * 100
print("A acurácia foi %.2f%%" % acuracia)

A acurácia foi 58.00%


In [12]:
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25, stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(raw_treino_x), len(raw_teste_x)))

scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

modelo = SVC(gamma='auto')
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 7500 elementos e testaremos com 2500 elementos
A acurácia foi 77.40%


In [13]:
raw_treino_x, raw_teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25, stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(raw_treino_x), len(raw_teste_x)))

scaler = StandardScaler()
scaler.fit(raw_treino_x)
treino_x = scaler.transform(raw_treino_x)
teste_x = scaler.transform(raw_teste_x)

modelo = DecisionTreeClassifier()
modelo.fit(raw_treino_x, treino_y)
previsoes = modelo.predict(raw_teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 7500 elementos e testaremos com 2500 elementos
A acurácia foi 71.72%


In [14]:
dot_data = export_graphviz(modelo)

In [15]:
grafico = graphviz.Source(dot_data)

In [16]:
grafico

In [17]:
treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, random_state = SEED, test_size = 0.25, stratify = y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo = LinearSVC(random_state = SEED)
modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % acuracia)

Treinaremos com 7500 elementos e testaremos com 2500 elementos
A acurácia foi 60.12%


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


In [18]:
# cross validation
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = 5, return_train_score=False)
print(results['test_score'])
media = results['test_score'].mean()
desvio = results['test_score'].std()
print(f"Acuracy com cross validation 5: {round((media - 2 * desvio)*100, 2)} e {round((media + 2 * desvio)*100, 2)} com media de {round(media * 100, 2)}")

[0.756  0.7565 0.7625 0.7545 0.7595]
Acuracy com cross validation 5: 75.21 e 76.35 com media de 75.78


# Aleatoridade com Cross validate

In [19]:
SEED = 301

cv = KFold(n_splits=10, shuffle=True)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = cv, return_train_score=False)
print(results['test_score'])
media = results['test_score'].mean()
desvio = results['test_score'].std()
print(f"Acuracy com cross validation 5: {round((media - 2 * desvio)*100, 2)} e {round((media + 2 * desvio)*100, 2)} com media de {round(media * 100, 2)}")


[0.765 0.764 0.758 0.742 0.764 0.752 0.763 0.747 0.76  0.763]
Acuracy com cross validation 5: 74.25 e 77.31 com media de 75.78


In [20]:
def imprime_results(results, cv):
    print(results['test_score'])
    media = results['test_score'].mean()
    desvio = results['test_score'].std()
    print(f"Acuracy com cross validation {cv}: {round((media - 2 * desvio)*100, 2)} e {round((media + 2 * desvio)*100, 2)} com media de {round(media * 100, 2)}")

In [21]:
# simular situacao de azar, pode ser azar como pode ser um desbalanceamento
dados.sort_values('vendido', ascending=True)

preco  vendido  idade       km_ano  modelo
4999  74023.29        0     12  24812.80412      12
5322  84843.49        0     13  23095.63834      15
5319  83100.27        0     19  36240.72746      22
5316  87932.13        0     16  32249.56426      17
5315  77937.01        0     15  28414.50704      18
...        ...      ...    ...          ...     ...
5491  71910.43        1      9  25778.40812      11
1873  30456.53        1      6  15468.97608       6
1874  69342.41        1     11  16909.33538      13
5499  70520.39        1     16  19622.68262      18
0     30941.02        1     18  35085.22134      21

[10000 rows x 5 columns]

In [22]:
dados_azar = dados.sort_values("vendido", ascending=True)
x_azar = dados_azar[["preco", "idade", "km_ano"]]
y_azar = dados_azar["vendido"]
dados_azar.head()


preco  vendido  idade       km_ano  modelo
4999  74023.29        0     12  24812.80412      12
5322  84843.49        0     13  23095.63834      15
5319  83100.27        0     19  36240.72746      22
5316  87932.13        0     16  32249.56426      17
5315  77937.01        0     15  28414.50704      18

In [23]:
SEED = 301

cv = KFold(n_splits = 10)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.447 0.409 0.438 0.446 0.694 0.663 0.668 0.673 0.67  0.676]
Acuracy com cross validation KFold(n_splits=10, random_state=None, shuffle=False): 34.29 e 81.39 com media de 57.84


In [24]:
cv = KFold(n_splits = 10, shuffle=True)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.784 0.749 0.744 0.767 0.77  0.746 0.78  0.759 0.737 0.742]
Acuracy com cross validation KFold(n_splits=10, random_state=None, shuffle=True): 72.62 e 78.94 com media de 75.78


In [25]:
cv = StratifiedKFold(n_splits = 10, shuffle=True)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.748 0.748 0.752 0.754 0.746 0.779 0.749 0.759 0.767 0.776]
Acuracy com cross validation StratifiedKFold(n_splits=10, random_state=None, shuffle=True): 73.48 e 78.08 com media de 75.78


In [26]:
cv = StratifiedKFold(n_splits = 10)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x_azar, y_azar, cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.744 0.759 0.763 0.765 0.754 0.742 0.771 0.748 0.764 0.768]
Acuracy com cross validation StratifiedKFold(n_splits=10, random_state=None, shuffle=False): 73.83 e 77.73 com media de 75.78


In [27]:
dados.modelo.value_counts()

20    868
19    832
18    753
21    725
17    710
16    676
15    612
14    591
13    577
22    562
12    469
11    408
10    389
23    378
9     312
8     261
24    211
7     204
6     181
5     134
4      79
3      44
2      21
1       3
Name: modelo, dtype: int64

In [28]:
cv = KFold(n_splits=10, shuffle=True)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.755 0.773 0.756 0.762 0.752 0.766 0.743 0.77  0.739 0.762]
Acuracy com cross validation KFold(n_splits=10, random_state=None, shuffle=True): 73.68 e 77.88 com media de 75.78


In [29]:
cv = StratifiedKFold(n_splits=10)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.742 0.77  0.749 0.764 0.761 0.764 0.754 0.755 0.759 0.76 ]
Acuracy com cross validation StratifiedKFold(n_splits=10, random_state=None, shuffle=False): 74.24 e 77.32 com media de 75.78


In [30]:
cv = GroupKFold(n_splits=10)
modelo = DecisionTreeClassifier(max_depth=2)
results = cross_validate(modelo, x, y, groups=dados.modelo,cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.78343313 0.75419546 0.74325674 0.79802956 0.75201613 0.71052632
 0.77575758 0.75686673 0.73502538 0.76721629]
Acuracy com cross validation GroupKFold(n_splits=10): 70.99 e 80.54 com media de 75.76


# Cross Validation StantardScaler

In [31]:
scaler = StandardScaler()
scaler.fit(treino_x)
treino_x_scaler = scaler.transform(treino_x)
teste_x_scaler = scaler.transform(teste_x)

modelo = SVC()
modelo.fit(treino_x_scaler, treino_y)
previsoes = modelo.predict(teste_x_scaler)
acuracia = accuracy_score(teste_y, previsoes) * 100
print("A acuracia foi de", acuracia)

A acuracia foi de 74.4


In [32]:
cv = GroupKFold(n_splits=10)
modelo = SVC()
results = cross_validate(modelo, x_azar, y_azar, groups=dados.modelo,cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.7744511  0.77591313 0.76723277 0.78128079 0.76612903 0.7854251
 0.77676768 0.75381485 0.78071066 0.76236663]
Acuracy com cross validation GroupKFold(n_splits=10): 75.38 e 79.1 com media de 77.24


In [33]:
scaler = StandardScaler()
scaler.fit(x_azar)
x_azar_escalado = scaler.transform(x_azar)
results = cross_validate(modelo, x_azar_escalado, y_azar, groups=dados.modelo,cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.76047904 0.76110563 0.76523477 0.77339901 0.76108871 0.77631579
 0.78282828 0.74974568 0.77969543 0.76236663]
Acuracy com cross validation GroupKFold(n_splits=10): 74.75 e 78.7 com media de 76.72


In [34]:
scaler = StandardScaler()
modelo = SVC()
pipeline = Pipeline([('transformacao', scaler), ('estimador', modelo)])
cv = GroupKFold(n_splits=10)
results = cross_validate(pipeline, x_azar, y_azar, groups=dados.modelo,cv = cv, return_train_score=False)
imprime_results(results, cv)

[0.76047904 0.76110563 0.76523477 0.77339901 0.76108871 0.77631579
 0.78282828 0.74872838 0.77969543 0.76236663]
Acuracy com cross validation GroupKFold(n_splits=10): 74.7 e 78.72 com media de 76.71
